spring:
  application:
    name: ToolsChallenge

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: tools_challenge
